import type { Metadata } from "next";
import "./globals.css";
import Header from "../components/Header"
import Footer from "../components/Footer"
import Nav from "../components/Nav";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        <Header/>
        <Nav/>
        <main className="flex-1 p-4 max-w-2xl mx-auto">
        {children}
        </main>
        <Footer/>
      </body>
    </html>
  );
}
